"""users table

Revision ID: 35d70c15b62f
Revises: 
Create Date: 2021-06-12 02:22:50.135271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35d70c15b62f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_identificacion', sa.String(length=180), nullable=False),
    sa.Column('numero_identificacion', sa.String(length=180), nullable=False),
    sa.Column('nombre', sa.String(length=180), nullable=False),
    sa.Column('edad', sa.String(length=180), nullable=False),
    sa.Column('celular', sa.String(length=180), nullable=False),
    sa.Column('direccion', sa.String(length=180), nullable=False),
    sa.Column('ciudad', sa.String(length=180), nullable=False),
    sa.Column('pais', sa.String(length=180), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_celular'), 'user', ['celular'], unique=False)
    op.create_index(op.f('ix_user_ciudad'), 'user', ['ciudad'], unique=False)
    op.create_index(op.f('ix_user_direccion'), 'user', ['direccion'], unique=False)
    op.create_index(op.f('ix_user_edad'), 'user', ['edad'], unique=False)
    op.create_index(op.f('ix_user_nombre'), 'user', ['nombre'], unique=False)
    op.create_index(op.f('ix_user_numero_identificacion'), 'user', ['numero_identificacion'], unique=True)
    op.create_index(op.f('ix_user_pais'), 'user', ['pais'], unique=False)
    op.create_index(op.f('ix_user_tipo_identificacion'), 'user', ['tipo_identificacion'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_tipo_identificacion'), table_name='user')
    op.drop_index(op.f('ix_user_pais'), table_name='user')
    op.drop_index(op.f('ix_user_numero_identificacion'), table_name='user')
    op.drop_index(op.f('ix_user_nombre'), table_name='user')
    op.drop_index(op.f('ix_user_edad'), table_name='user')
    op.drop_index(op.f('ix_user_direccion'), table_name='user')
    op.drop_index(op.f('ix_user_ciudad'), table_name='user')
    op.drop_index(op.f('ix_user_celular'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
